name: sport_and_gamification
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  user_repository:
    path: user_repository

  repository:
    path: repository

  flutter_bloc: ^2.0.1

  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  cloud_firestore: ^0.12.10+2

  json_annotation: ^3.0.0
  font_awesome_flutter: ^8.4.0

  equatable: ^1.0.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
