name: repository
description: Model
version: 1.0.0

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  json_serializable: ^3.2.3
  cloud_firestore: ^0.12.10+2

dev_dependencies:
  build_runner: ^1.0.0
